// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qinmgvigdydlchcenrbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpbm1ndmlnZHlkbGNoY2VucmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTI3OTMsImV4cCI6MjA3MDI4ODc5M30._UZsPVrWcLFqlSgIasRIPalcQIzpy21bjTkTZntn86A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});